#!/bin/sh

# Get the current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Extract the branch number (assuming it follows the pattern "feat/1-tata", "bugfix/2-foo", etc.)
branch_number=$(echo "$branch_name" | grep -o -E '[0-9]+')

# File with the commit message
commit_msg_file=$1

# Read the current commit message
commit_msg=$(cat "$commit_msg_file")

# Prepend the branch number to the commit message if a branch number is found and it is not an empty commit message
if [ -n "$branch_number" ] && [ -s "$commit_msg_file" ]; then
    echo "[#$branch_number] $commit_msg" > "$commit_msg_file"
fi
